### ISSUE TITLE
`enqueue` is a mutable behavior but with a immutable function type

### ISSUE THREAD

**Issue by yanganto** [lightningdevkit/lightning-liquidity#76]
The [`enqueue`](https://github.com/lightningdevkit/lightning-liquidity/blob/587ffe78b6b966a6dcd9ae7fd64cb32c86d503c4/src/message_queue.rs#L19C2-L19C19 ) function of the public trait MessageQueue is immutable.  In general, we do mutate some data from the Queue, when we put things into it.

**Comment by yanganto** [comment]
It may be an intentional design to keep the mutability inside.  The thing I should use is `TestMessageQueue`, but the test queue is private, and the trait is public.

**Comment by tnull** [comment]
> It may be an intentional design to keep the mutability inside. The thing I should use is `TestMessageQueue`, but the test queue is private, and the trait is public.

It is in fact intentional. As noted in #73,  the trait was introduced essentially as an intermediate step when moving the `PeerManager` dependency from all of the message handlers to just one place: the message queue. However, users probably wouldn't benefit from using a custom `MessageQueue` implementation, which is why we're considering to just remove it again and just use `DefaultMessageQueue` everywhere.

**Comment by yanganto** [comment]
Got it
